name: Build & Publish

on:
  push:
    branches:
      - v5-rework
  pull_request:
    branches:
      - v5-rework

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mysql, mysqlnd, sqlite3, bcmath, gd, curl, zip, openssl, mbstring, xml
      - uses: actions/checkout@v2
      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Install NPM Dependencies
        run: npm install
      - name: Build Site
        run: npm run production
      - name: Prepare production
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add build_production -f && git commit -m "Build for deploy"
      - name: Deploy website
        run: |
          git remote set-url origin https://${{secrets.DEPLOY_KEY}}@github.com/YOUR_USERNAME/REPOSITORY_NAME.git
          git subtree split --prefix build_production -b gh-pages
          git push -f origin gh-pages:gh-pages